### ISSUE TITLE
FLOOD FILL ALGO IN CPP

### ISSUE THREAD

**Issue by 2SkeePeR2** [gdsc-gvp/Problem-Solving#13]
### Problem Link 
https://leetcode.com/problems/flood-fill/

### Coding platform
Leetcode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python

### Additional context (OPTIONAL)
This is a good problem to learn and understand applications of BFS and how it works.
![Screenshot from 2021-10-01 08-51-57](https://user-images.githubusercontent.com/58355537/135560476-d9a9e671-5058-478f-8b6e-6c363c7ebfbb.png)
.

**Comment by deephunt3r** [comment]
Assigned! pls mention in which language your working
