### ISSUE TITLE
Change PR template

### ISSUE THREAD

**Issue by 2SkeePeR2** [gdsc-gvp/Problem-Solving#15]
### Problem Link 
Add language used in pull_request_template

### Additional context
Right now the PR template lacks the ```language used``` subsection. It should be added to the PR template as contributors also need to add the language used

**Comment by deephunt3r** [comment]
Can you describe it more

**Comment by 2SkeePeR2** [comment]
Should I also add JS ?

**Comment by deephunt3r** [comment]
> Should I also add JS ?

let me confirm it from the maintainer @tireless-22
