### ISSUE TITLE
Dislikes of 3

### ISSUE THREAD

**Issue by prampratap30** [gdsc-gvp/Problem-Solving#22]
### Problem Link
[1560A](https://codeforces.com/problemset/problem/1560/A)

### Coding platform

Codeforces

### Programming language

C++17

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
- [ ] JavaScript

### Additional context (OPTIONAL)

This is an implementation based problem.

**Comment by deephunt3r** [comment]
you can go now

**Comment by prampratap30** [comment]
Thanks!

**Comment by prampratap30** [comment]
Btw guys, just wanted to let you know that, if you close the pull request, then it's automatically labelled as spam by hacktoberfest. 
![Capture](https://user-images.githubusercontent.com/44699710/135640047-edb38b20-7493-4f00-9fa0-e8d3450b7539.JPG)
