### ISSUE TITLE
Add Mutations in python

### ISSUE THREAD

**Issue by SURYACODER** [gdsc-gvp/Problem-Solving#24]
### Problem Link

https://www.hackerrank.com/challenges/python-mutations/problem

### Coding platform
Hacker rank

### Programming language

- [ ] C
- [ ] C++
- [ ] Java
- [X] Python
- [ ] JavaScript

**Comment by tireless-22** [comment]
Hey, @SURYACODER don't make PR directly . We have to check whether the problem is already there or not .After that we will assign you solve this issue

**Comment by tireless-22** [comment]
hackerearth
peoblem name folder(create one)
