### ISSUE TITLE
MAXIMUM PRODUCT SUBARRAY

### ISSUE THREAD

**Issue by 2SkeePeR2** [gdsc-gvp/Problem-Solving#29]
### Problem Link

https://leetcode.com/problems/maximum-product-subarray/

### Coding platform

Leetcode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
- [ ] JavaScript

### Additional context (OPTIONAL)

This is a good problem that helps in building a foundation in DP.

**Comment by tireless-22** [comment]
proceed!
