### ISSUE TITLE
SERIALIZE AND DESERIALIZE BINARY TREE

### ISSUE THREAD

**Issue by 2SkeePeR2** [gdsc-gvp/Problem-Solving#32]
### Problem Link

https://leetcode.com/problems/serialize-and-deserialize-binary-tree/

### Coding platform

Leetcode

### Programming language

- [ ] C
- [x] C++
- [ ] Java
- [ ] Python
- [ ] JavaScript

**Comment by Shubhambawner** [comment]
hey can someone please tell what dose this 5 tasks/ 10 tasks mean?

**Comment by deephunt3r** [comment]
> hey can someone please tell what dose this 5 tasks/ 10 tasks mean?

@Shubhambawner There are some choices like which language you prefer like C/CPP etc in issues 
and same as in PR with relevant choices
